[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
final_transfer_tracker = "2RF9K6PH8AT3mMrnMrvSNDuNeQPeXuqmiNMJRBGgLa2a"

[programs.mainnet]
final_transfer_tracker = "CPdJTxNtRtuS3WnpnmNnxmf4VNEm7StKfVpv2SCYSLK9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "./mainnet-deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
