[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
final_transfer_tracker = "2K3rtnK7jN3BmFvPW4coMiF31noaXuaER6N4edNJZm7N"

[programs.mainnet]
final_transfer_tracker = "2vAaF2P7QriWd5VJioSoiyBdU1ieU7mQX5qCp3djD61G"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "./mainnet-deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
